annotations:
  artifacthub.io/links: |
    - name: Image source
      url: https://github.com/itzg/docker-minecraft-server
    - name: Image DockerHub
      url: https://hub.docker.com/r/itzg/minecraft-server
apiVersion: v1
appVersion: SeeValues
description: Minecraft server
home: https://minecraft.net/
keywords:
- game
- server
maintainers:
- email: gtaylor@gc-taylor.com
  name: gtaylor
- email: jeff@billimek.com
  name: billimek
- email: itzgeoff@gmail.com
  name: itzg
name: minecraft
sources:
- https://github.com/itzg/minecraft-server-charts
version: 3.1.6
